const tileWidth = 16 * 2 * 7.5; // 192
const tileHeight = 16 * 7.5; // 96
// const tileWidth = 16 * 2 * 3.8; // 192
// const tileHeight = 16 * 3.8; // 96
const nRows = 16; // 17 - 1
const nCols = 26; // 27 - 1
// const map = new Array(nRows).fill().map(() => new Array(nCols).fill(0));
// const locationsMap = new Array(nRows)
//   .fill()
//   .map(() => new Array(nCols).fill(null));

const offset = { x: 0, y: 0 };
let isDragginMap = false;
let isDragginPlayerMenu = false;
const mouseStartPos = { x: undefined, y: undefined };

const map = [
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
    0,
  ],
  [
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
    0,
  ],
  [
    0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
    0,
  ],
  [
    0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
    0,
  ],
  [
    1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
    0,
  ],
  [
    0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0,
  ],
];
const locationsMap = [
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    10,
    null,
    null,
    null,
    null,
    null,
    null,
    3,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    18,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    5,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    16,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    13,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    14,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    12,
    null,
    null,
    null,
    7,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    6,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    11,
    null,
    null,
    null,
  ],
  [
    null,
    9,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    null,
    null,
    null,
    null,
    15,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    8,
    null,
    null,
    17,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    1,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    2,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    19,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    4,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
];
const locations = [
  { name: "Banheiro Público", diseases: [13, 14], img: "banheiro-publico.png" },
  { name: "Bar", diseases: [1, 7, 13], img: "bar.png" },
  { name: "Bueiro", diseases: [0, 2, 12], img: "bueiro.png" },
  {
    name: "Carrinho de Lanche",
    diseases: [1, 7, 9],
    img: "carrinho-lanche.png",
  },
  { name: "Casa", diseases: [3, 9, 13, 14, 16], img: "casa.png" },
  { name: "Chafariz", diseases: [0, 1, 2], img: "chafariz.png" },
  { name: "Container de Lixo", diseases: [2, 12], img: "container-lixo.png" },
  { name: "Escola", diseases: [7, 9, 10, 13, 16], img: "escola.png" },
  { name: "Lagoa", diseases: [4, 5, 8, 12], img: "lagoa.png" },
  { name: "Loja", diseases: [10, 13, 16], img: "loja.png" },
  { name: "Mata Pequena", diseases: [4, 5, 6, 8, 11, 15], img: "mata-pequena.png" },
  { name: "Motel", diseases: [14, 16], img: "motel.png" },
  { name: "Padaria", diseases: [9, 13], img: "padaria.png" },
  { name: "Parquinho Infantil", diseases: [2, 9, 15], img: "parque-infantil.png" },
  { name: "Poça de água", diseases: [2, 4, 12], img: "poca-agua.png" },
  { name: "Restaurante", diseases: [1, 7, 9, 13], img: "restaurante.png" },
  { name: "Rio / Esgoto", diseases: [1, 4, 12], img: "esgoto.png" },
  { name: "Salão de Beleza", diseases: [10, 13], img: "salao-beleza.png" },
  { name: "Sítio peri-urbano", diseases: [3, 5, 6, 8, 11], img: "sitio.png" },
  { name: "Zoológico", diseases: [2, 6, 11, 15], img: "zoologico.png" },
];

const diseases = [
  {
    name: "Chikungunya",
    symptoms: [
      "Artralgia debilitante",
      "Cefaleia (dor de cabeça)",
      "Conjuntivite",
      "Dor retro-orbital (dor atrás dos olhos)",
      "Edema articular (inchaço nas articulações)",
      "Fadiga",
      "Febre alta",
      "Mal-estar",
      "Mialgia (dor muscular)",
      "Náuseas",
      "Vômitos",
      "Artralgia debilitante, persistente ou recorrente (dor nas articulações)",
      "Edema articular persistente",
      "Rigidez matinal",
      "Fadiga crônica",
      "Dores musculares leves intermitentes",
    ],
    description:
      "A chikungunya é uma doença viral causada pelo vírus chikungunya (CHIKV) e é transmitida pela picada da fêmea infectada do mosquito Aedes aegypti, que também transmite a dengue.",
  },
  {
    name: "Cólera",
    symptoms: [
      "Diarreia aquosa",
      "Náuseas",
      "Vômitos",
      "Dor abdominal",
      "Mal-estar",
      "Prostração",
      "Desidratação severa",
      "Anúria (produção baixa ou ausência de urina)",
    ],
    description:
      "A cólera é uma doença infecciosa intestinal aguda causada pela bactéria Vibrio cholerae (sorogrupos O1 e O139) e transmitida pela via fecal-oral. Isso ocorre principalmente pela ingestão de água ou alimentos contaminados por fezes ou vômitos de pessoas infectadas, como peixes, frutos do mar crus ou mal cozidos, ou pelo contato direto (mão-boca) com superfícies ou pessoas contaminadas quando a higiene é inadequada.",
  },
  {
    name: "Dengue",
    symptoms: [
      "Febre alta",
      "Cefaleia intensa (dor de cabeça)",
      "Dor retro-orbital (dor atrás dos olhos)",
      "Mialgia (dor muscular)",
      "Artralgia (dor nas articulações)",
      "Náuseas",
      "Vômitos",
      "Mal-estar",
      "Prostração",
      "Letargia leve",
      "Dor abdominal intensa e contínua",
      "Vômitos persistentes",
      "Petéquias (pequenas manchas vermelhas)",
      "Hemorragias",
      "Letargia intensa",
      "Fadiga",
      "Fraqueza",
      "Perda de apetite",
    ],
    description:
      "A dengue é uma doença febril aguda causada pelo vírus da dengue (DENV), que possui quatro sorotipos principais (DENV-1, DENV-2, DENV-3 e DENV-4). Ela é classificada como uma arbovirose, sendo transmitida para os humanos principalmente pela picada da fêmea infectada do mosquito Aedes aegypti.",
  },
  {
    name: "Esporotricose",
    symptoms: [
      "Lesão cutânea nodular",
      'Linfangite ascendente ("corda" sob a pele)',
      "Nódulos em cadeia",
      "Úlceras crônicas",
      "Nódulos persistentes",
      "Fibrose",
    ],
    description:
      "A Esporotricose é uma micose causada por fungos do gênero Sporothrix e sua transmissão pode acontecer de duas formas principais: pelo contato da pele com materiais contaminados do ambiente, como solo, plantas e espinhos; ou, mais comumente atualmente, pela arranhadura ou mordedura de gatos infectados. A doença não é transmitida diretamente de pessoa para pessoa",
  },
  {
    name: "Esquistossomose",
    symptoms: [
      "Dermatite Cercariana (coceira e erupção no local da infecção)",
      "Febre alta",
      "Tosse",
      "Mal-estar",
      "Diarréia",
      "Dor abdominal",
      "Fadiga",
      "Esplenomegalia (aumento do baço)",
      "Hepatomegalia (aumento do fígado)",
      "Hipertensão portal",
      "Vômitos com sangue",
      "Ascite (barriga d’água)",
      "Fibrose hepática",
    ],
    description:
      "A esquistossomose é uma doença parasitária causada pelo verme Schistosoma mansoni. O ciclo da doença começa quando uma pessoa infectada elimina ovos do parasita pelas fezes. Ao entrarem em contato com a água, esses ovos liberam larvas que infectam caramujos. Dentro do caramujo, as larvas se desenvolvem e são liberadas novamente na água na forma de cercárias, que são as formas infectantes. A infecção humana ocorre quando a pele entra em contato direto com água doce parada ou de pouca correnteza contaminada por cercárias, que penetram ativamente na pele",
  },
  {
    name: "Febre Amarela",
    symptoms: [
      "Febre alta",
      "Cefaleia",
      "Calafrios",
      "Mal-estar",
      "Mialgia (dor no corpo)",
      "Náuseas",
      "Vômitos",
      "Prostração",
      "Icterícia (pele e olhos amarelados)",
      "Insuficiência hepática",
      "Aumento do fígado",
      "Vômito negro (hemorragia no estômago)",
      "Hemorragias",
      "Vômitos persistentes",
      "Insuficiência renal",
      "Anúria (ausência de urina)",
    ],
    description:
      "A Febre Amarela é uma doença infecciosa causada pelo vírus YFV, transmitido pela picada de mosquitos. No ciclo silvestre (vigente), mosquitos dos gêneros Haemagogus e Sabethes, de áreas de matas, transmitem o vírus, tendo os macacos como hospedeiros principais. Já no ciclo urbano o mosquito transmissor é o Aedes aegypti, porém casos não são registrados desde 1942 no Brasil.",
  },
  {
    name: "Febre Maculosa",
    symptoms: [
      "Cefaleia (dor de cabeça)",
      "Exantema maculopapular",
      "Febre alta",
      "Mal-estar",
      "Picada de carrapato",
      "Vômitos",
    ],
    description:
      "A Febre Maculosa é uma doença infecciosa grave causada por bactérias do gênero Rickettsia e transmitida exclusivamente pela picada de carrapatos infectados, principalmente da espécie Amblyomma, conhecida como carrapato-estrela. A transmissão só acontece quando o carrapato permanece fixo na pele por horas (entre 4 e 10 horas), e nunca ocorre diretamente de pessoa para pessoa ou pelo contato com animais doentes",
  },
  {
    name: "Febre Tifóide",
    symptoms: [
      "Febre",
      "Mal-estar",
      "Cefaleia (dor de cabeça)",
      "Mialgia (dor muscular)",
      "Anorexia (perda de apetite)",
      "Constipação",
      "Febre alta",
      "Dor abdominal",
      "Roséolas tíficas",
      "Bradicardia relativa (pulsos lentos em relação à febre)",
      "Hepatomegalia (aumento do fígado)",
      "Esplenomegalia (aumento do baço)",
      "Confusão mental intensa",
      "Perfuração intestinal",
      "Hemorragias",
      "Choque ou colapso circulatório",
      "Fadiga",
    ],
    description:
      "A Febre Tifóide é uma doença infecciosa aguda causada pela bactéria Salmonella enterica sorotipo Typhi (S. Typhi). A transmissão ocorre pela via fecal-oral, ou seja, pela ingestão de água ou alimentos contaminados com fezes ou urina de pessoas doentes ou portadoras assintomáticas, ou ainda pelo contato direto (mão-boca) com superfícies ou pessoas contaminadas quando os hábitos de higiene são inadequados",
  },
  {
    name: "Hantavirose",
    symptoms: [
      "Febre",
      "Mialgia intensa (dor muscular)",
      "Cefaleia (dor de cabeça)",
      "Calafrios",
      "Tontura",
      "Dor abdominal",
      "Náusea",
      "Vômitos",
      "Tosse seca",
      "Dispneia (falta de ar)",
      "Edema pulmonar não cardiogênico",
      "Insuficiência renal aguda",
      "Insuficiência respiratória",
    ],
    description:
      "A Hantavirose é uma doença viral grave causada pelos vírus do gênero Ortho Hantavirus, e transmitida por roedores silvestres, principalmente ao inalar poeira contaminada com suas fezes, urina ou saliva seca.",
  },
  {
    name: "Hepatite A",
    symptoms: [
      "Febre",
      "Anorexia (perda de apetite)",
      "Náuseas",
      "Vômitos",
      "Mialgia",
      "Fadiga",
      "Dor abdominal",
      "Icterícia (pele e olhos amarelados)",
      "Colúria (urina escura)",
      "Acolia fecal (fezes claras)",
      "Aumento do fígado (hepatomegalia)",
      "Dor abdominal (pode continuar)",
      "Fadiga (pode ser intensa)",
      "Fadiga",
      "Apetite reduzido",
    ],
    description:
      "A Hepatite A é uma doença infecciosa causada pelo vírus da Hepatite A (VHA), que é transmitido pela via fecal-oral. A principal forma de contágio ocorre por meio da ingestão de água ou alimentos contaminados com fezes de uma pessoa infectada, ou pelo contato direto (mão-boca) com objetos, superfícies ou de pessoa para pessoa, quando os hábitos de higiene, como lavar as mãos, não são adequadamente seguidos.",
  },
  {
    name: "Meningite meningocócica",
    symptoms: [
      "Febre alta",
      "Cefaleia intensa (dor de cabeça)",
      "Rigidez de nuca",
      "Fotofobia (sensibilidade excessiva à luz)",
      "Vômitos",
      "Mal-estar",
      "Letargia",
      "Confusão mental / estupor",
      "Convulsões",
      "Náuseas",
      "Petéquias (pequenas manchas vermelhas)",
    ],
    description:
      "A Meningite Meningocócica é uma infecção grave causada pela bactéria Neisseria meningitidis. Sua transmissão ocorre de pessoa para pessoa por via respiratória, através do contato próximo e prolongado com gotículas e secreções da garganta ou nariz de uma pessoa infectada ou portadora da bactéria, como ao tossir, espirrar ou beijar",
  },
  {
    name: "Leishmaniose tegumentar",
    symptoms: [
      "Lesão ulcerada (ferida) que não cicatriza",
      "Coriza (inflamação da mucosa nasal)",
      "Lesão ulcerada persistente",
      "Coriza crônica",
      "Hemorragia nasal",
      "Tosse",
      "Obstrução nasal",
      "Deformidades nas mucosas",
    ],
    description:
      "A Leishmaniose é uma doença causada pelo parasita Leishmania, transmitida exclusivamente pela picada da fêmea do mosquito-palha (flebotomíneo). O ciclo envolve animais: o mosquito se infecta ao picar um mamífero reservatório (como raposas silvestres ou, nas cidades, os cães domésticos) e depois transmite o parasita a um novo hospedeiro, que pode ser uma pessoa.",
  },
  {
    name: "Leptospirose",
    symptoms: [
      "Febre alta",
      "Calafrios",
      "Cefaleia (dor de cabeça)",
      "Mialgia intensa (dor muscular)",
      "Dor na panturrilha",
      "Mal-estar",
      "Náuseas",
      "Vômitos",
      "Exantema (erupção cutânea)",
      "Icterícia (coloração amarela da pele e olhos)",
      "Insuficiência renal aguda",
      "Anúria (produlção baixa ou ausência de urina)",
      "Hemorragia pulmonar",
      "Hepatomegalia (aumento do fígado)",
      "Hepatite",
    ],
    description:
      "A leptospirose é uma infecção bacteriana aguda causada por bactérias do gênero Leptospira que é transmitida pelo contato da pele ou mucosas com água, lama ou solo contaminados pela urina de animais infectados, principalmente ratos, especialmente durante enchentes e inundações.",
  },
  {
    name: "Sarampo",
    symptoms: [
      "Febre alta",
      "Tosse",
      "Coriza (inflamação da mucosa nasal)",
      "Conjuntivite",
      "Manchas de Koplik (pequenos pontos vermelhos com o centro branco na mucosa bucal)",
      "Erupção cutânea maculopapular (exantema - vermelhidão)",
      "Encefalite (inflamação do encéfalo)",
      "Pneumonia",
      "PEES - Panencefalite esclerosante subaguda (doença neurológica)",
    ],
    description:
      "O sarampo é uma doença infecciosa e altamente contagiosa causada pelo vírus do sarampo (gênero Morbillivirus). A transmissão ocorre de pessoa para pessoa por via aérea, por meio de secreções expelidas ao tossir, falar ou respirar.",
  },
  {
    name: "Sífilis",
    symptoms: [
      "Úlcera única (lesão indolor)",
      "Linfadenopatia (aumento dos linfonodos)",
      "Exantema (erupção cutânea)",
      "Febre",
      "Mal-estar",
      "Artralgia (dor articular)",
      "Cefaleia (dor de cabeça)",
      "Perda de cabelo",
      "Lesões mucosas (placas mucosas)",
      "Condiloma lata (lesões úmidas brancas ou acinzentadas)",
      "Goma (granuloma tardio)",
      "Acometimento cardiovascular",
    ],
    description:
      "A sífilis é uma Infecção Sexualmente Transmissível (IST) causada pela bactéria Treponema pallidum. A principal forma de transmissão é pelo contato sexual desprotegido (vaginal, anal ou oral) com uma pessoa infectada. A doença também pode ser transmitida da mãe para o bebê durante a gestação ou o parto, o que configura a sífilis congênita",
  },
  {
    name: "Toxoplasmose",
    symptoms: [
      "Febre",
      "Mal-estar",
      "Fadiga",
      "Mialgia (dor muscular)",
      "Linfadenopatia cervical (aumento dos linfonodos)",
      "Faringite (inflamação da faringe)",
      "Aumento do baço (Esplenomegalia)",
      "Cefaleia (dor de cabeça)",
      "Confusão",
      "Convulsões",
    ],
    description:
      "A toxoplasmose é uma doença infecciosa causada pelo protozoário Toxoplasma gondii. A forma mais comum de transmissão é pela ingestão de oocistos (ovos do parasita) presentes em alimentos, água ou solo contaminados por fezes de gatos infectados. Outras vias importantes são o consumo de carne crua ou malcozida de animais portadores (especialmente suína e ovina) e a transmissão congênita, da gestante infectada para o feto",
  },
  {
    name: "Tuberculose pulmonar",
    symptoms: [
      "Febre vespertina",
      "Tosse seca",
      "Mal-estar",
      "Fadiga",
      "Anorexia (perda de apetite)",
      "Sudorese noturna",
      "Perda de peso",
      "Tosse produtiva",
      "Hemoptise (tosse com sangue)",
      "Sudorese noturna intensa",
      "Fraqueza",
      "Dor torácica",
      "Dispneia (falta de ar)",
    ],
    description:
      "A tuberculose pulmonar é uma doença infecciosa e transmissível causada pela bactéria Mycobacterium tuberculosis (também chamada de bacilo de Koch). Sua transmissão ocorre por via respiratória (aérea), quando uma pessoa com a forma ativa da doença, ao tossir, falar ou espirrar, elimina no ar aerossóis contendo o agente infeccioso que podem ser inalados por outras pessoas.",
  },
];

const people = [
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
];
