const tileWidth = 16 * 2 * 3.8; // 192
const tileHeight = 16 * 3.8; // 96
const nRows = 16; // 17 - 1
const nCols = 26; // 27 - 1
// const map = new Array(nRows).fill().map(() => new Array(nCols).fill(0));

const offset = { x: 0, y: 0 };
let isDraggin = false;
const mouseStartPos = { x: undefined, y: undefined };

const map = [
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
    0,
  ],
  [
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
    0,
  ],
  [
    0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
    0,
  ],
  [
    0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
    0,
  ],
  [
    1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
    0,
  ],
  [
    0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
    0,
  ],
];
const locationsMap = [
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    3,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    9,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    1,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    4,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    17,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    16,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    null,
    null,
    null,
    20,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    2,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    14,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    6,
    null,
    null,
    null,
    5,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    15,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    10,
    null,
    null,
    null,
    null,
    19,
    null,
    null,
    null,
    null,
    null,
    13,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    12,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    8,
    null,
    7,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    11,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    18,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
];
const locations = [
  { name: "Banheiro Público", diseases: [13, 14] },
  { name: "Bar", diseases: [1, 7, 13] },
  { name: "Bueiro", diseases: [0, 2, 12] },
  { name: "Casa", diseases: [3, 9, 13, 14, 16] },
  { name: "Carrinho de Lanche", diseases: [1, 7, 9] },
  { name: "Chafariz", diseases: [0, 1, 2] },
  { name: "Container de Lixo", diseases: [2, 12] },
  { name: "Escola", diseases: [7, 9, 10, 13, 16] },
  { name: "Lagoa", diseases: [4, 5, 8, 12] },
  { name: "Loja", diseases: [10, 13, 16] },
  { name: "Mata Pequena", diseases: [4, 5, 6, 8, 11, 15] },
  { name: "Padaria", diseases: [9, 13] },
  { name: "Parquinho Infantil", diseases: [2, 9, 15] },
  { name: "Poça de água", diseases: [2, 4, 12] },
  { name: "Restaurante", diseases: [1, 7, 9, 13] },
  { name: "Rio / Esgoto", diseases: [1, 4, 12] },
  { name: "Rua", diseases: [0, 2, 3] },
  { name: "Sítio peri-urbano", diseases: [3, 5, 6, 8, 11] },
  { name: "Zoologico", diseases: [2, 6, 11, 15] },
  { name: "Salão de Beleza", diseases: [10, 13] },
  { name: "Motel", diseases: [14, 16] },
];

const disease = [
  { name: "Chikungunya" },
  { name: "Cólera" },
  { name: "Dengue" },
  { name: "Esporotricose" },
  { name: "Esquistossomose" },
  { name: "Febre Amarela" },
  { name: "Febre Maculosa" },
  { name: "Febre Tifóide" },
  { name: "Hantavirose" },
  { name: "Hepatite A" },
  { name: "Meningite" },
  { name: "Leishmaniose" },
  { name: "Leptospirose" },
  { name: "Sarampo" },
  { name: "Sífilis" },
  { name: "Toxoplasmose" },
  { name: "Tuberculose" },
];
const people = [
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
];
