// const tileWidth = 16 * 2 * 7.5; // 192
// const tileHeight = 16 * 7.5; // 96
const tileWidth = 16 * 2 * 3.8; // 192
const tileHeight = 16 * 3.8; // 96
const nRows = 16; // 17 - 1
const nCols = 26; // 27 - 1
// const map = new Array(nRows).fill().map(() => new Array(nCols).fill(0));
// const locationsMap = new Array(nRows)
//   .fill()
//   .map(() => new Array(nCols).fill(null));

const offset = { x: 0, y: 0 };
let isDragginMap = false;
let isDragginPlayerMenu = false;
const mouseStartPos = { x: undefined, y: undefined };

const map = [
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
    0,
  ],
  [
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
    0,
  ],
  [
    0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
    0,
  ],
  [
    0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
    0,
  ],
  [
    1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
    0,
  ],
  [
    0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
    0,
  ],
  [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0,
  ],
];
const locationsMap = [
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    3,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    9,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    1,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    4,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    17,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    16,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    null,
    null,
    null,
    20,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    2,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    14,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    6,
    null,
    null,
    null,
    5,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    15,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    10,
    null,
    null,
    null,
    null,
    19,
    null,
    null,
    null,
    null,
    null,
    13,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    12,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    8,
    null,
    7,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    11,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    18,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
];

const locations = [
  { name: "Banheiro Público", diseases: [13, 14] },
  { name: "Bar", diseases: [1, 7, 13] },
  { name: "Bueiro", diseases: [0, 2, 12] },
  { name: "Casa", diseases: [3, 9, 13, 14, 16] },
  { name: "Carrinho de Lanche", diseases: [1, 7, 9] },
  { name: "Chafariz", diseases: [0, 1, 2] },
  { name: "Container de Lixo", diseases: [2, 12] },
  { name: "Escola", diseases: [7, 9, 10, 13, 16] },
  { name: "Lagoa", diseases: [4, 5, 8, 12] },
  { name: "Loja", diseases: [10, 13, 16] },
  { name: "Mata Pequena", diseases: [4, 5, 6, 8, 11, 15] },
  { name: "Padaria", diseases: [9, 13] },
  { name: "Parquinho Infantil", diseases: [2, 9, 15] },
  { name: "Poça de água", diseases: [2, 4, 12] },
  { name: "Restaurante", diseases: [1, 7, 9, 13] },
  { name: "Rio / Esgoto", diseases: [1, 4, 12] },
  { name: "Rua", diseases: [0, 2, 3] },
  { name: "Sítio peri-urbano", diseases: [3, 5, 6, 8, 11] },
  { name: "Zoologico", diseases: [2, 6, 11, 15] },
  { name: "Salão de Beleza", diseases: [10, 13] },
  { name: "Motel", diseases: [14, 16] },
];

const diseases = [
  {
    name: "Chikungunya",
    symptoms: [
      "Artralgia debilitante",
      "Cefaleia (dor de cabeça)",
      "Conjuntivite",
      "Dor retro-orbital (dor atrás dos olhos)",
      "Edema articular (inchaço nas articulações)",
      "Fadiga",
      "Febre alta",
      "Mal-estar",
      "Mialgia (dor muscular)",
      "Náuseas",
      "Vômitos",
      "Artralgia debilitante, persistente ou recorrente (dor nas articulações)",
      "Edema articular persistente",
      "Rigidez matinal",
      "Fadiga crônica",
      "Dores musculares leves intermitentes",
    ],
  },
  {
    name: "Cólera",
    symptoms: [
      "Diarreia aquosa",
      "Náuseas",
      "Vômitos",
      "Dor abdominal",
      "Mal-estar",
      "Prostração",
      "Desidratação severa",
      "Anúria (produção baixa ou ausência de urina)",
    ],
  },
  {
    name: "Dengue",
    symptoms: [
      "Febre alta",
      "Cefaleia intensa (dor de cabeça)",
      "Dor retro-orbital (dor atrás dos olhos)",
      "Mialgia (dor muscular)",
      "Artralgia (dor nas articulações)",
      "Náuseas",
      "Vômitos",
      "Mal-estar",
      "Prostração",
      "Letargia leve",
      "Dor abdominal intensa e contínua",
      "Vômitos persistentes",
      "Petéquias (pequenas manchas vermelhas)",
      "Hemorragias",
      "Letargia intensa",
      "Fadiga",
      "Fraqueza",
      "Perda de apetite",
    ],
  },
  {
    name: "Esporotricose",
    symptoms: [
      "Lesão cutânea nodular",
      'Linfangite ascendente ("corda" sob a pele)',
      "Nódulos em cadeia",
      "Úlceras crônicas",
      "Nódulos persistentes",
      "Fibrose",
    ],
  },
  {
    name: "Esquistossomose",
    symptoms: [
      "Dermatite Cercariana (coceira e erupção no local da infecção)",
      "Febre alta",
      "Tosse",
      "Mal-estar",
      "Diarréia",
      "Dor abdominal",
      "Fadiga",
      "Esplenomegalia (aumento do baço)",
      "Hepatomegalia (aumento do fígado)",
      "Hipertensão portal",
      "Vômitos com sangue",
      "Ascite (barriga d’água)",
      "Fibrose hepática",
    ],
  },
  {
    name: "Febre Amarela",
    symptoms: [
      "Febre alta",
      "Cefaleia",
      "Calafrios",
      "Mal-estar",
      "Mialgia (dor no corpo)",
      "Náuseas",
      "Vômitos",
      "Prostração",
      "Icterícia (pele e olhos amarelados)",
      "Insuficiência hepática",
      "Aumento do fígado",
      "Vômito negro (hemorragia no estômago)",
      "Hemorragias",
      "Vômitos persistentes",
      "Insuficiência renal",
      "Anúria (ausência de urina)",
    ],
  },
  {
    name: "Febre Maculosa",
    symptoms: [
      "Cefaleia (dor de cabeça)",
      "Exantema maculopapular",
      "Febre alta",
      "Mal-estar",
      "Picada de carrapato",
      "Vômitos",
    ],
  },
  {
    name: "Febre Tifóide",
    symptoms: [
      "Febre",
      "Mal-estar",
      "Cefaleia (dor de cabeça)",
      "Mialgia (dor muscular)",
      "Anorexia (perda de apetite)",
      "Constipação",
      "Febre alta",
      "Dor abdominal",
      "Roséolas tíficas",
      "Bradicardia relativa (pulsos lentos em relação à febre)",
      "Hepatomegalia (aumento do fígado)",
      "Esplenomegalia (aumento do baço)",
      "Confusão mental intensa",
      "Perfuração intestinal",
      "Hemorragias",
      "Choque ou colapso circulatório",
      "Fadiga",
    ],
  },
  {
    name: "Hantavirose",
    symptoms: [
      "Febre",
      "Mialgia intensa (dor muscular)",
      "Cefaleia (dor de cabeça)",
      "Calafrios",
      "Tontura",
      "Dor abdominal",
      "Náusea",
      "Vômitos",
      "Tosse seca",
      "Dispneia (falta de ar)",
      "Edema pulmonar não cardiogênico",
      "Insuficiência renal aguda",
      "Insuficiência respiratória",
    ],
  },
  {
    name: "Hepatite A",
    symptoms: [
      "Febre",
      "Anorexia (perda de apetite)",
      "Náuseas",
      "Vômitos",
      "Mialgia",
      "Fadiga",
      "Dor abdominal",
      "Icterícia (pele e olhos amarelados)",
      "Colúria (urina escura)",
      "Acolia fecal (fezes claras)",
      "Aumento do fígado (hepatomegalia)",
      "Dor abdominal (pode continuar)",
      "Fadiga (pode ser intensa)",
      "Fadiga",
      "Apetite reduzido",
    ],
  },
  {
    name: "Meningite",
    symptoms: [
      "Febre alta",
      "Cefaleia intensa (dor de cabeça)",
      "Rigidez de nuca",
      "Fotofobia (sensibilidade excessiva à luz)",
      "Vômitos",
      "Mal-estar",
      "Letargia",
      "Confusão mental / estupor",
      "Convulsões",
      "Náuseas",
      "Petéquias (pequenas manchas vermelhas)",
    ],
  },
  {
    name: "Leishmaniose tegumentar",
    symptoms: [
      "Lesão ulcerada (ferida) que não cicatriza",
      "Coriza (inflamação da mucosa nasal)",
      "Lesão ulcerada persistente",
      "Coriza crônica",
      "Hemorragia nasal",
      "Tosse",
      "Obstrução nasal",
      "Deformidades nas mucosas",
    ],
  },
  {
    name: "Leptospirose",
    symptoms: [
      "Febre alta",
      "Calafrios",
      "Cefaleia (dor de cabeça)",
      "Mialgia intensa (dor muscular)",
      "Dor na panturrilha",
      "Mal-estar",
      "Náuseas",
      "Vômitos",
      "Exantema (erupção cutânea)",
      "Icterícia (coloração amarela da pele e olhos)",
      "Insuficiência renal aguda",
      "Anúria (produlção baixa ou ausência de urina)",
      "Hemorragia pulmonar",
      "Hepatomegalia (aumento do fígado)",
      "Hepatite",
    ],
  },
  {
    name: "Sarampo",
    symptoms: [
      "Febre alta",
      "Tosse",
      "Coriza (inflamação da mucosa nasal)",
      "Conjuntivite",
      "Manchas de Koplik (pequenos pontos vermelhos com o centro branco na mucosa bucal)",
      "Erupção cutânea maculopapular (exantema - vermelhidão)",
      "Encefalite (inflamação do encéfalo)",
      "Pneumonia",
      "PEES - Panencefalite esclerosante subaguda (doença neurológica)",
    ],
  },
  {
    name: "Sífilis",
    symptoms: [
      "Úlcera única (lesão indolor)",
      "Linfadenopatia (aumento dos linfonodos)",
      "Exantema (erupção cutânea)",
      "Febre",
      "Mal-estar",
      "Artralgia (dor articular)",
      "Cefaleia (dor de cabeça)",
      "Perda de cabelo",
      "Lesões mucosas (placas mucosas)",
      "Condiloma lata (lesões úmidas brancas ou acinzentadas)",
      "Goma (granuloma tardio)",
      "Acometimento cardiovascular",
    ],
  },
  {
    name: "Toxoplasmose",
    symptoms: [
      "Febre",
      "Mal-estar",
      "Fadiga",
      "Mialgia (dor muscular)",
      "Linfadenopatia cervical (aumento dos linfonodos)",
      "Faringite (inflamação da faringe)",
      "Aumento do baço (Esplenomegalia)",
      "Cefaleia (dor de cabeça)",
      "Confusão",
      "Convulsões",
    ],
  },
  {
    name: "Tuberculose pulmonar",
    symptoms: [
      "Febre vespertina",
      "Tosse seca",
      "Mal-estar",
      "Fadiga",
      "Anorexia (perda de apetite)",
      "Sudorese noturna",
      "Perda de peso",
      "Tosse produtiva",
      "Hemoptise (tosse com sangue)",
      "Sudorese noturna intensa",
      "Fraqueza",
      "Dor torácica",
      "Dispneia (falta de ar)",
    ],
  },
];

const people = [
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
  { name: crypto.randomUUID(), age: Math.floor(Math.random() * 50 + 20) },
];
